name: Tetris
version: '1.0'
main: me.dylan.tetris.Tetris
api-version: 1.16
commands:
  tetris:
    description: 테트리스 게임 플레이
#    usage: "/<command> [quit|help]"
#    usage: "/<command> [<player_ign>|<null>]"
    permission: tetris.play

permissions:
  tetris.play:
    description: 테트리스 게임을 플레이할 수 있는 권한
    default: true
