# 테트리스 게임 설정
settings:
  board:
    width: 10
    height: 20
  game:
    initial-level: 1
    level-up-lines: 10
    enable-sound: true
    enable-particles: true

# 점수 설정
scoring:
  single-line: 100
  double-line: 300
  triple-line: 500
  tetris: 800
